/**
 * LIGS waitlist confirmation email — same artifact as the free WHOIS report.
 * Subject: "Your identity query has been logged"
 * Body: Generated by renderFreeWhoisReport(report) from lib/free-whois-report (single template).
 *
 * Sender verification:
 * - Resend: Default FROM (onboarding@resend.dev) is allowed without verification. Custom domain/address must be verified in Resend dashboard.
 * - SendGrid: The FROM address (or domain) must be a verified sender identity in SendGrid. Unverified sender causes reject or non-delivery.
 *
 * PRODUCTION CHECKLIST (confirmation email sends):
 * - BLOB_READ_WRITE_TOKEN — required in /api/waitlist before insert (not in this module).
 * - RESEND_API_KEY or SENDGRID_API_KEY — required; otherwise send skipped with reason provider_key_missing.
 * - EMAIL_FROM — optional; unverified sender causes provider_rejected.
 * - NEXT_PUBLIC_SITE_URL or VERCEL_URL — optional; fallback https://ligs.io for absolute artifact URLs in HTML.
 */

/** Result of sendWaitlistConfirmation — machine-readable reason for API/client observability. */
export type WaitlistConfirmationResult = {
  sent: boolean;
  reason: "sent" | "provider_key_missing" | "provider_rejected" | "provider_error";
};

import { IGNIS_V1_ARTIFACTS } from "@/lib/exemplar-store";
import {
  getArchetypePublicAssetUrlWithRotation,
  getArchetypePublicAssetUrls,
} from "@/lib/archetype-public-assets";
import type { FreeWhoisReport } from "@/lib/free-whois-report";
import { renderFreeWhoisReport, renderFreeWhoisReportText } from "@/lib/free-whois-report";

const DEFAULT_FROM = "LIGS <onboarding@resend.dev>";

const SITE_URL =
  (typeof process.env.NEXT_PUBLIC_SITE_URL === "string" && process.env.NEXT_PUBLIC_SITE_URL.trim()) ||
  (typeof process.env.VERCEL_URL === "string" && process.env.VERCEL_URL.trim()
    ? `https://${process.env.VERCEL_URL}`
    : "") ||
  "https://ligs.io";

/** Deterministic seed for registry email artifact selection. Same person + archetype → same image. */
const REGISTRY_EMAIL_ARTIFACT_SEED_SUFFIX = ":registry-email";

/**
 * Resolve the best registry artifact image URL for the recipient.
 * Order: (1) Ignis uses v1 share card; (2) other archetypes use public shareCard with rotation; (3) exemplarCard if no shareCard; (4) fallback Ignis v1 share card.
 */
export function getRegistryArtifactImageUrl(
  preview_archetype: string | undefined,
  email: string
): string {
  const fallback = IGNIS_V1_ARTIFACTS.finalBeautyField;

  const raw = preview_archetype?.trim();
  if (!raw) return fallback;

  const archetype = normalizeArchetypeKey(raw);
  if (!archetype) return fallback;

  if (archetype === "Ignispectrum") return IGNIS_V1_ARTIFACTS.finalBeautyField;

  const seed = `${email}:${archetype}${REGISTRY_EMAIL_ARTIFACT_SEED_SUFFIX}`;
  const shareCard = getArchetypePublicAssetUrlWithRotation(archetype, "shareCard", seed);
  if (shareCard) return toAbsoluteUrl(shareCard);
  const urls = getArchetypePublicAssetUrls(archetype);
  if (urls?.shareCard) return toAbsoluteUrl(urls.shareCard);
  if (urls?.exemplarCard) return toAbsoluteUrl(urls.exemplarCard);
  return fallback;
}

function normalizeArchetypeKey(raw: string): string | null {
  if (ARCHETYPE_KEYS[raw as keyof typeof ARCHETYPE_KEYS]) return raw;
  const lower = raw.toLowerCase();
  const found = Object.keys(ARCHETYPE_KEYS).find((k) => k.toLowerCase() === lower);
  return found ?? null;
}

const ARCHETYPE_KEYS: Record<string, true> = {
  Aequilibris: true,
  Duplicaris: true,
  Fluxionis: true,
  Ignispectrum: true,
  Innovaris: true,
  Obscurion: true,
  Precisura: true,
  Radiantis: true,
  Stabiliora: true,
  Structoris: true,
  Tenebris: true,
  Vectoris: true,
};

function toAbsoluteUrl(path: string): string {
  const base = SITE_URL.replace(/\/$/, "");
  const p = path.startsWith("/") ? path : `/${path}`;
  return `${base}${p}`;
}

/**
 * Send waitlist confirmation email. Body is the free WHOIS report (renderFreeWhoisReport).
 * Caller must pass the same report object used for the in-page free report; report.artifactImageUrl must be set.
 */
export async function sendWaitlistConfirmation(
  email: string,
  report: FreeWhoisReport
): Promise<WaitlistConfirmationResult> {
  const resendKey = process.env.RESEND_API_KEY?.trim();
  const sendgridKey = process.env.SENDGRID_API_KEY?.trim();

  /** Mask for logs only — never log API keys. */
  const maskedTo =
    email.length > 4 ? email.charAt(0) + "***@" + (email.split("@")[1] ?? "") : "***";

  if (!resendKey && !sendgridKey) {
    console.warn(
      "[waitlist] confirmation provider=none reason=provider_key_missing to=" +
        maskedTo +
        " from_attempt=n/a"
    );
    return { sent: false, reason: "provider_key_missing" };
  }

  const from = process.env.EMAIL_FROM?.trim() || DEFAULT_FROM;
  const subject = "Your identity query has been logged";
  const html = renderFreeWhoisReport(report, { siteUrl: SITE_URL });
  const text = renderFreeWhoisReportText(report, { siteUrl: SITE_URL });

  if (resendKey) {
    const fromValue = from.includes("<") ? from : `LIGS <${from}>`;
    const fromForLog = fromValue.replace(/</g, "").replace(/>/g, "");
    console.log(
      "[waitlist] confirmation provider_selected=resend to=" +
        maskedTo +
        " from_attempt=" +
        fromForLog
    );
    let res: Response;
    try {
      res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: fromValue,
        to: [email],
        subject,
        html,
        text,
      }),
    });
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.error(
        "[waitlist] confirmation provider=resend reason=provider_error to=" +
          maskedTo +
          " from_attempt=" +
          fromForLog +
          " error=" +
          msg.slice(0, 120)
      );
      return { sent: false, reason: "provider_error" };
    }
    const bodyText = await res.text();
    let bodyJson: { id?: string } | null = null;
    try {
      bodyJson = bodyText ? JSON.parse(bodyText) : null;
    } catch {
      // ignore
    }
    if (res.ok) {
      console.log(
        "[waitlist] confirmation reason=sent provider=resend to=" +
          maskedTo +
          " from=" +
          fromForLog +
          " status=" +
          res.status +
          (bodyJson?.id ? " id=" + bodyJson.id : "")
      );
      return { sent: true, reason: "sent" };
    }
    console.error(
      "[waitlist] confirmation reason=provider_rejected provider=resend to=" +
        maskedTo +
        " from=" +
        fromForLog +
        " status=" +
        res.status +
        " body=" +
        bodyText.slice(0, 200)
    );
    return { sent: false, reason: "provider_rejected" };
  }

  console.log(
    "[waitlist] confirmation provider_selected=sendgrid to=" +
      maskedTo +
      " from_attempt=" +
      (from.includes("<") ? from.replace(/^[^<]*<([^>]+)>$/, "$1").trim() : from)
  );

  const fromEmail = from.includes("<") ? from.replace(/^[^<]*<([^>]+)>$/, "$1").trim() : from;
  const fromName = from.includes("<") ? from.replace(/\s*<[^>]+>$/, "").trim() : "LIGS";
  let res: Response;
  try {
    res = await fetch("https://api.sendgrid.com/v3/mail/send", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${sendgridKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      personalizations: [{ to: [{ email }], subject }],
      from: { email: fromEmail, name: fromName },
      content: [
        { type: "text/html", value: html },
        { type: "text/plain", value: text },
      ],
    }),
  });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error(
      "[waitlist] confirmation reason=provider_error provider=sendgrid to=" +
        maskedTo +
        " from=" +
        fromEmail +
        " error=" +
        msg.slice(0, 120)
    );
    return { sent: false, reason: "provider_error" };
  }
  const bodyText = await res.text();
  if (res.ok) {
    console.log(
      "[waitlist] confirmation reason=sent provider=sendgrid to=" +
        maskedTo +
        " from=" +
        fromEmail +
        " status=" +
        res.status
    );
    return { sent: true, reason: "sent" };
  }
  console.error(
    "[waitlist] confirmation reason=provider_rejected provider=sendgrid to=" +
      maskedTo +
      " from=" +
      fromEmail +
      " status=" +
      res.status +
      " body=" +
      bodyText.slice(0, 200)
  );
  return { sent: false, reason: "provider_rejected" };
}
